const vocabularyData = [
  // --- หมวด 1: Daily Life (ชีวิตประจำวัน) 50 คำ ---
  { id: 1, word: "Always", pos: "adv.", translation: "เสมอ", example: "She always wakes up early.", category: "Daily Life" },
  { id: 2, word: "Answer", pos: "v.", translation: "ตอบ", example: "Please answer the phone.", category: "Daily Life" },
  { id: 3, word: "Ask", pos: "v.", translation: "ถาม", example: "Can I ask a question?", category: "Daily Life" },
  { id: 4, word: "Bath", pos: "n.", translation: "การอาบน้ำ", example: "I take a warm bath.", category: "Daily Life" },
  { id: 5, word: "Begin", pos: "v.", translation: "เริ่มต้น", example: "Class will begin soon.", category: "Daily Life" },
  { id: 6, word: "Brush", pos: "v.", translation: "แปรง", example: "Brush your teeth daily.", category: "Daily Life" },
  { id: 7, word: "Buy", pos: "v.", translation: "ซื้อ", example: "I need to buy food.", category: "Daily Life" },
  { id: 8, word: "Clean", pos: "adj.", translation: "สะอาด", example: "Keep your room clean.", category: "Daily Life" },
  { id: 9, word: "Cook", pos: "v.", translation: "ทำอาหาร", example: "He loves to cook dinner.", category: "Daily Life" },
  { id: 10, word: "Dance", pos: "v.", translation: "เต้นรำ", example: "They dance at the party.", category: "Daily Life" },
  { id: 11, word: "Drink", pos: "v.", translation: "ดื่ม", example: "Drink plenty of water.", category: "Daily Life" },
  { id: 12, word: "Drive", pos: "v.", translation: "ขับรถ", example: "She drives to work.", category: "Daily Life" },
  { id: 13, word: "Eat", pos: "v.", translation: "กิน", example: "We eat lunch together.", category: "Daily Life" },
  { id: 14, word: "Exercise", pos: "n.", translation: "การออกกำลังกาย", example: "Exercise is good for health.", category: "Daily Life" },
  { id: 15, word: "Finish", pos: "v.", translation: "เสร็จสิ้น", example: "Finish your homework first.", category: "Daily Life" },
  { id: 16, word: "Forget", pos: "v.", translation: "ลืม", example: "Don't forget your keys.", category: "Daily Life" },
  { id: 17, word: "Help", pos: "v.", translation: "ช่วยเหลือ", example: "Can you help me?", category: "Daily Life" },
  { id: 18, word: "Learn", pos: "v.", translation: "เรียนรู้", example: "I want to learn English.", category: "Daily Life" },
  { id: 19, word: "Listen", pos: "v.", translation: "ฟัง", example: "Listen to the teacher.", category: "Daily Life" },
  { id: 20, word: "Live", pos: "v.", translation: "อยู่อาศัย", example: "They live in Bangkok.", category: "Daily Life" },
  { id: 21, word: "Open", pos: "v.", translation: "เปิด", example: "Open the door please.", category: "Daily Life" },
  { id: 22, word: "Read", pos: "v.", translation: "อ่าน", example: "Read a book every day.", category: "Daily Life" },
  { id: 23, word: "Remember", pos: "v.", translation: "จดจำ", example: "I remember your name.", category: "Daily Life" },
  { id: 24, word: "Run", pos: "v.", translation: "วิ่ง", example: "He runs in the park.", category: "Daily Life" },
  { id: 25, word: "Sleep", pos: "v.", translation: "นอนหลับ", example: "Sleep for eight hours.", category: "Daily Life" },
  { id: 26, word: "Speak", pos: "v.", translation: "พูด", example: "She speaks three languages.", category: "Daily Life" },
  { id: 27, word: "Study", pos: "v.", translation: "เรียน", example: "Study hard for tests.", category: "Daily Life" },
  { id: 28, word: "Talk", pos: "v.", translation: "สนทนา", example: "Let's talk about it.", category: "Daily Life" },
  { id: 29, word: "Think", pos: "v.", translation: "คิด", example: "I think it is good.", category: "Daily Life" },
  { id: 30, word: "Understand", pos: "v.", translation: "เข้าใจ", example: "Do you understand?", category: "Daily Life" },
  { id: 31, word: "Walk", pos: "v.", translation: "เดิน", example: "Walk to the shop.", category: "Daily Life" },
  { id: 32, word: "Wash", pos: "v.", translation: "ล้าง", example: "Wash your hands.", category: "Daily Life" },
  { id: 33, word: "Watch", pos: "v.", translation: "ดู", example: "Watch TV at night.", category: "Daily Life" },
  { id: 34, word: "Work", pos: "v.", translation: "ทำงาน", example: "He works in an office.", category: "Daily Life" },
  { id: 35, word: "Write", pos: "v.", translation: "เขียน", example: "Write a letter home.", category: "Daily Life" },
  { id: 36, word: "Morning", pos: "n.", translation: "ตอนเช้า", example: "Good morning class.", category: "Daily Life" },
  { id: 37, word: "Night", pos: "n.", translation: "กลางคืน", example: "Good night everyone.", category: "Daily Life" },
  { id: 38, word: "Home", pos: "n.", translation: "บ้าน", example: "Stay at home today.", category: "Daily Life" },
  { id: 39, word: "Friend", pos: "n.", translation: "เพื่อน", example: "She is my best friend.", category: "Daily Life" },
  { id: 40, word: "Family", pos: "n.", translation: "ครอบครัว", example: "I love my family.", category: "Daily Life" },
  { id: 41, word: "Money", pos: "n.", translation: "เงิน", example: "Save your money.", category: "Daily Life" },
  { id: 42, word: "Time", pos: "n.", translation: "เวลา", example: "What time is it?", category: "Daily Life" },
  { id: 43, word: "Today", pos: "n.", translation: "วันนี้", example: "Today is Monday.", category: "Daily Life" },
  { id: 44, word: "Tomorrow", pos: "n.", translation: "พรุ่งนี้", example: "See you tomorrow.", category: "Daily Life" },
  { id: 45, word: "Yesterday", pos: "n.", translation: "เมื่อวาน", example: "I saw him yesterday.", category: "Daily Life" },
  { id: 46, word: "Week", pos: "n.", translation: "สัปดาห์", example: "Next week is busy.", category: "Daily Life" },
  { id: 47, word: "Month", pos: "n.", translation: "เดือน", example: "This month is cold.", category: "Daily Life" },
  { id: 48, word: "Year", pos: "n.", translation: "ปี", example: "Happy new year.", category: "Daily Life" },
  { id: 49, word: "Life", pos: "n.", translation: "ชีวิต", example: "Enjoy your life.", category: "Daily Life" },
  { id: 50, word: "Habit", pos: "n.", translation: "นิสัย", example: "Reading is a good habit.", category: "Daily Life" },

  // --- หมวด 2: Food & Drink (อาหารและเครื่องดื่ม) 50 คำ ---
  { id: 51, word: "Apple", pos: "n.", translation: "แอปเปิ้ล", example: "An apple a day.", category: "Food & Drink" },
  { id: 52, word: "Banana", pos: "n.", translation: "กล้วย", example: "Monkeys like bananas.", category: "Food & Drink" },
  { id: 53, word: "Bread", pos: "n.", translation: "ขนมปัง", example: "Toast the bread.", category: "Food & Drink" },
  { id: 54, word: "Butter", pos: "n.", translation: "เนย", example: "Spread butter on bread.", category: "Food & Drink" },
  { id: 55, word: "Cake", pos: "n.", translation: "เค้ก", example: "Chocolate cake is delicious.", category: "Food & Drink" },
  { id: 56, word: "Cheese", pos: "n.", translation: "ชีส", example: "I love cheese pizza.", category: "Food & Drink" },
  { id: 57, word: "Chicken", pos: "n.", translation: "ไก่", example: "Fried chicken for dinner.", category: "Food & Drink" },
  { id: 58, word: "Coffee", pos: "n.", translation: "กาแฟ", example: "Hot coffee in morning.", category: "Food & Drink" },
  { id: 59, word: "Egg", pos: "n.", translation: "ไข่", example: "Boil an egg please.", category: "Food & Drink" },
  { id: 60, word: "Fish", pos: "n.", translation: "ปลา", example: "Fresh fish from sea.", category: "Food & Drink" },
  { id: 61, word: "Fruit", pos: "n.", translation: "ผลไม้", example: "Eat healthy fruit.", category: "Food & Drink" },
  { id: 62, word: "Ice", pos: "n.", translation: "น้ำแข็ง", example: "Put ice in juice.", category: "Food & Drink" },
  { id: 63, word: "Juice", pos: "n.", translation: "น้ำผลไม้", example: "Orange juice is sweet.", category: "Food & Drink" },
  { id: 64, word: "Meat", pos: "n.", translation: "เนื้อสัตว์", example: "Cook the meat well.", category: "Food & Drink" },
  { id: 65, word: "Milk", pos: "n.", translation: "นม", example: "Drink milk before sleep.", category: "Food & Drink" },
  { id: 66, word: "Noodle", pos: "n.", translation: "ก๋วยเตี๋ยว", example: "Thai style noodle soup.", category: "Food & Drink" },
  { id: 67, word: "Rice", pos: "n.", translation: "ข้าว", example: "Steamed jasmine rice.", category: "Food & Drink" },
  { id: 68, word: "Salad", pos: "n.", translation: "สลัด", example: "Green salad is fresh.", category: "Food & Drink" },
  { id: 69, word: "Soup", pos: "n.", translation: "ซุป", example: "Hot chicken soup.", category: "Food & Drink" },
  { id: 70, word: "Tea", pos: "n.", translation: "ชา", example: "Green tea with lemon.", category: "Food & Drink" },
  { id: 71, word: "Water", pos: "n.", translation: "น้ำ", example: "Pure drinking water.", category: "Food & Drink" },
  { id: 72, word: "Sugar", pos: "n.", translation: "น้ำตาล", example: "Too much sugar is bad.", category: "Food & Drink" },
  { id: 73, word: "Salt", pos: "n.", translation: "เกลือ", example: "Add a pinch of salt.", category: "Food & Drink" },
  { id: 74, word: "Pepper", pos: "n.", translation: "พริกไทย", example: "Black pepper on steak.", category: "Food & Drink" },
  { id: 75, word: "Pork", pos: "n.", translation: "เนื้อหมู", example: "Grilled pork chops.", category: "Food & Drink" },
  { id: 76, word: "Beef", pos: "n.", translation: "เนื้อวัว", example: "Beef burger with fries.", category: "Food & Drink" },
  { id: 77, word: "Vegetable", pos: "n.", translation: "ผัก", example: "Eat fresh vegetables.", category: "Food & Drink" },
  { id: 78, word: "Tomato", pos: "n.", translation: "มะเขือเทศ", example: "Red ripe tomato.", category: "Food & Drink" },
  { id: 79, word: "Potato", pos: "n.", translation: "มันฝรั่ง", example: "Mashed potato side dish.", category: "Food & Drink" },
  { id: 80, word: "Onion", pos: "n.", translation: "หัวหอม", example: "Chop the onion finely.", category: "Food & Drink" },
  { id: 81, word: "Garlic", pos: "n.", translation: "กระเทียม", example: "Garlic adds good flavor.", category: "Food & Drink" },
  { id: 82, word: "Orange", pos: "n.", translation: "ส้ม", example: "Sweet juicy orange.", category: "Food & Drink" },
  { id: 83, word: "Grape", pos: "n.", translation: "องุ่น", example: "Purple seedless grapes.", category: "Food & Drink" },
  { id: 84, word: "Mango", pos: "n.", translation: "มะม่วง", example: "Ripe mango with rice.", category: "Food & Drink" },
  { id: 85, word: "Lemon", pos: "n.", translation: "มะนาว", example: "Lemon is very sour.", category: "Food & Drink" },
  { id: 86, word: "Sweet", pos: "adj.", translation: "หวาน", example: "This candy is sweet.", category: "Food & Drink" },
  { id: 87, word: "Sour", pos: "adj.", translation: "เปรี้ยว", example: "Sour lime juice.", category: "Food & Drink" },
  { id: 88, word: "Bitter", pos: "adj.", translation: "ขม", example: "Black coffee is bitter.", category: "Food & Drink" },
  { id: 89, word: "Spicy", pos: "adj.", translation: "เผ็ด", example: "Spicy Tom Yum soup.", category: "Food & Drink" },
  { id: 90, word: "Salty", pos: "adj.", translation: "เค็ม", example: "Potato chips are salty.", category: "Food & Drink" },
  { id: 91, word: "Breakfast", pos: "n.", translation: "อาหารเช้า", example: "Eat breakfast early.", category: "Food & Drink" },
  { id: 92, word: "Lunch", pos: "n.", translation: "อาหารกลางวัน", example: "Lunch at noon.", category: "Food & Drink" },
  { id: 93, word: "Dinner", pos: "n.", translation: "อาหารเย็น", example: "Family dinner time.", category: "Food & Drink" },
  { id: 94, word: "Snack", pos: "n.", translation: "ขนมขบเคี้ยว", example: "Healthy afternoon snack.", category: "Food & Drink" },
  { id: 95, word: "Dessert", pos: "n.", translation: "ของหวาน", example: "Ice cream for dessert.", category: "Food & Drink" },
  { id: 96, word: "Hungry", pos: "adj.", translation: "หิว", example: "I am very hungry.", category: "Food & Drink" },
  { id: 97, word: "Thirsty", pos: "adj.", translation: "กระหายน้ำ", example: "Thirsty after running.", category: "Food & Drink" },
  { id: 98, word: "Delicious", pos: "adj.", translation: "อร่อย", example: "This meal is delicious.", category: "Food & Drink" },
  { id: 99, word: "Menu", pos: "n.", translation: "เมนู", example: "Read the food menu.", category: "Food & Drink" },
  { id: 100, word: "Order", pos: "v.", translation: "สั่งอาหาร", example: "Ready to order food.", category: "Food & Drink" },

  // --- หมวด 3: Travel & Places (การเดินทางและสถานที่) 50 คำ ---
  { id: 101, word: "Airport", pos: "n.", translation: "สนามบิน", example: "Arrive at airport early.", category: "Travel & Places" },
  { id: 102, word: "Bus", pos: "n.", translation: "รถประจำทาง", example: "Take the city bus.", category: "Travel & Places" },
  { id: 103, word: "Car", pos: "n.", translation: "รถยนต์", example: "Park the red car.", category: "Travel & Places" },
  { id: 104, word: "City", pos: "n.", translation: "เมือง", example: "Big crowded city.", category: "Travel & Places" },
  { id: 105, word: "Country", pos: "n.", translation: "ประเทศ", example: "Visit a new country.", category: "Travel & Places" },
  { id: 106, word: "Hotel", pos: "n.", translation: "โรงแรม", example: "Book a hotel room.", category: "Travel & Places" },
  { id: 107, word: "Map", pos: "n.", translation: "แผนที่", example: "Check the road map.", category: "Travel & Places" },
  { id: 108, word: "Park", pos: "n.", translation: "สวนสาธารณะ", example: "Walk in the park.", category: "Travel & Places" },
  { id: 109, word: "Plane", pos: "n.", translation: "เครื่องบิน", example: "Board the plane now.", category: "Travel & Places" },
  { id: 110, word: "Road", pos: "n.", translation: "ถนน", example: "Cross the busy road.", category: "Travel & Places" },
  { id: 111, word: "School", pos: "n.", translation: "โรงเรียน", example: "Students go to school.", category: "Travel & Places" },
  { id: 112, word: "Station", pos: "n.", translation: "สถานี", example: "Train station platform.", category: "Travel & Places" },
  { id: 113, word: "Street", pos: "n.", translation: "ถนน/ซอย", example: "Walk down the street.", category: "Travel & Places" },
  { id: 114, word: "Ticket", pos: "n.", translation: "ตั๋ว", example: "Show your entrance ticket.", category: "Travel & Places" },
  { id: 115, word: "Train", pos: "n.", translation: "รถไฟ", example: "Fast express train.", category: "Travel & Places" },
  { id: 116, word: "Travel", pos: "v.", translation: "ท่องเที่ยว", example: "Love to travel world.", category: "Travel & Places" },
  { id: 117, word: "Visit", pos: "v.", translation: "เยี่ยมชม", example: "Visit museum today.", category: "Travel & Places" },
  { id: 118, word: "Beach", pos: "n.", translation: "ชายหาด", example: "Sandy ocean beach.", category: "Travel & Places" },
  { id: 119, word: "Mountain", pos: "n.", translation: "ภูเขา", example: "Climb high mountain.", category: "Travel & Places" },
  { id: 120, word: "River", pos: "n.", translation: "แม่น้ำ", example: "Boat on the river.", category: "Travel & Places" },
  { id: 121, word: "Sea", pos: "n.", translation: "ทะเล", example: "Swim in the sea.", category: "Travel & Places" },
  { id: 122, word: "Island", pos: "n.", translation: "เกาะ", example: "Tropical paradise island.", category: "Travel & Places" },
  { id: 123, word: "Bridge", pos: "n.", translation: "สะพาน", example: "Cross over the bridge.", category: "Travel & Places" },
  { id: 124, word: "Building", pos: "n.", translation: "อาคาร", example: "Tall modern building.", category: "Travel & Places" },
  { id: 125, word: "Hospital", pos: "n.", translation: "โรงพยาบาล", example: "Doctors at hospital.", category: "Travel & Places" },
  { id: 126, word: "Market", pos: "n.", translation: "ตลาด", example: "Buy food at market.", category: "Travel & Places" },
  { id: 127, word: "Museum", pos: "n.", translation: "พิพิธภัณฑ์", example: "History art museum.", category: "Travel & Places" },
  { id: 128, word: "Restaurant", pos: "n.", translation: "ร้านอาหาร", example: "Dine at restaurant.", category: "Travel & Places" },
  { id: 129, word: "Shop", pos: "n.", translation: "ร้านค้า", example: "Gift shop nearby.", category: "Travel & Places" },
  { id: 130, word: "Zoo", pos: "n.", translation: "สวนสัตว์", example: "See animals at zoo.", category: "Travel & Places" },
  { id: 131, word: "Bank", pos: "n.", translation: "ธนาคาร", example: "Withdraw cash from bank.", category: "Travel & Places" },
  { id: 132, word: "Temple", pos: "n.", translation: "วัด", example: "Ancient Thai temple.", category: "Travel & Places" },
  { id: 133, word: "Passport", pos: "n.", translation: "หนังสือเดินทาง", example: "Keep passport safe.", category: "Travel & Places" },
  { id: 134, word: "Luggage", pos: "n.", translation: "กระเป๋าเดินทาง", example: "Pack your luggage.", category: "Travel & Places" },
  { id: 135, word: "Flight", pos: "n.", translation: "เที่ยวบิน", example: "Direct flight to Tokyo.", category: "Travel & Places" },
  { id: 136, word: "Taxi", pos: "n.", translation: "รถแท็กซี่", example: "Call a yellow taxi.", category: "Travel & Places" },
  { id: 137, word: "Ship", pos: "n.", translation: "เรือใหญ่", example: "Cruise ship on ocean.", category: "Travel & Places" },
  { id: 138, word: "Boat", pos: "n.", translation: "เรือ", example: "Row a small boat.", category: "Travel & Places" },
  { id: 139, word: "Bicycle", pos: "n.", translation: "รถจักรยาน", example: "Ride bicycle in park.", category: "Travel & Places" },
  { id: 140, word: "Walk", pos: "v.", translation: "เดินเท้า", example: "Walk along footpath.", category: "Travel & Places" },
  { id: 141, word: "North", pos: "n.", translation: "ทิศเหนือ", example: "Travel to the north.", category: "Travel & Places" },
  { id: 142, word: "South", pos: "n.", translation: "ทิศใต้", example: "Warm southern beaches.", category: "Travel & Places" },
  { id: 143, word: "East", pos: "n.", translation: "ทิศตะวันออก", example: "Sun rises in east.", category: "Travel & Places" },
  { id: 144, word: "West", pos: "n.", translation: "ทิศตะวันตก", example: "Sun sets in west.", category: "Travel & Places" },
  { id: 145, word: "Left", pos: "n.", translation: "ซ้าย", example: "Turn left at corner.", category: "Travel & Places" },
  { id: 146, word: "Right", pos: "n.", translation: "ขวา", example: "Turn right next signal.", category: "Travel & Places" },
  { id: 147, word: "Straight", pos: "adv.", translation: "ตรงไป", example: "Go straight ahead.", category: "Travel & Places" },
  { id: 148, word: "Near", pos: "prep.", translation: "ใกล้", example: "Hotel is near station.", category: "Travel & Places" },
  { id: 149, word: "Far", pos: "adj.", translation: "ไกล", example: "Is it far from here?", category: "Travel & Places" },
  { id: 150, word: "Where", pos: "adv.", translation: "ที่ไหน", example: "Where is the bathroom?", category: "Travel & Places" },

  // --- หมวด 4: Technology & Science (เทคโนโลยีและวิทยาศาสตร์) 50 คำ ---
  { id: 151, word: "Computer", pos: "n.", translation: "คอมพิวเตอร์", example: "Use computer for work.", category: "Technology & Science" },
  { id: 152, word: "Internet", pos: "n.", translation: "อินเทอร์เน็ต", example: "Connect to high speed internet.", category: "Technology & Science" },
  { id: 153, word: "Phone", pos: "n.", translation: "โทรศัพท์", example: "Smart mobile phone.", category: "Technology & Science" },
  { id: 154, word: "Screen", pos: "n.", translation: "หน้าจอ", example: "Bright display screen.", category: "Technology & Science" },
  { id: 155, word: "Website", pos: "n.", translation: "เว็บไซต์", example: "Browse useful website.", category: "Technology & Science" },
  { id: 156, word: "Data", pos: "n.", translation: "ข้อมูล", example: "Save data to cloud.", category: "Technology & Science" },
  { id: 157, word: "File", pos: "n.", translation: "ไฟล์", example: "Download project file.", category: "Technology & Science" },
  { id: 158, word: "Code", pos: "n.", translation: "โค้ด/รหัส", example: "Write clean software code.", category: "Technology & Science" },
  { id: 159, word: "Robot", pos: "n.", translation: "หุ่นยนต์", example: "Smart modern robot.", category: "Technology & Science" },
  { id: 160, word: "Space", pos: "n.", translation: "อวกาศ", example: "Explore outer space.", category: "Technology & Science" },
  { id: 161, word: "Energy", pos: "n.", translation: "พลังงาน", example: "Clean solar energy.", category: "Technology & Science" },
  { id: 162, word: "System", pos: "n.", translation: "ระบบ", example: "Operating system update.", category: "Technology & Science" },
  { id: 163, word: "App", pos: "n.", translation: "แอปพลิเคชัน", example: "Install new mobile app.", category: "Technology & Science" },
  { id: 164, word: "Mouse", pos: "n.", translation: "เมาส์", example: "Click with optical mouse.", category: "Technology & Science" },
  { id: 165, word: "Keyboard", pos: "n.", translation: "แป้นพิมพ์", example: "Type on wireless keyboard.", category: "Technology & Science" },
  { id: 166, word: "Digital", pos: "adj.", translation: "ดิจิทัล", example: "Digital age technology.", category: "Technology & Science" },
  { id: 167, word: "Network", pos: "n.", translation: "เครือข่าย", example: "Secure computer network.", category: "Technology & Science" },
  { id: 168, word: "Program", pos: "n.", translation: "โปรแกรม", example: "Run python program.", category: "Technology & Science" },
  { id: 169, word: "Battery", pos: "n.", translation: "แบตเตอรี่", example: "Full battery charge.", category: "Technology & Science" },
  { id: 170, word: "Camera", pos: "n.", translation: "กล้องถ่ายรูป", example: "HD digital camera.", category: "Technology & Science" },
  { id: 171, word: "Device", pos: "n.", translation: "อุปกรณ์", example: "Smart electronic device.", category: "Technology & Science" },
  { id: 172, word: "Email", pos: "n.", translation: "อีเมล", example: "Send business email.", category: "Technology & Science" },
  { id: 173, word: "Online", pos: "adj.", translation: "ออนไลน์", example: "Online learning portal.", category: "Technology & Science" },
  { id: 174, word: "Password", pos: "n.", translation: "รหัสผ่าน", example: "Strong secret password.", category: "Technology & Science" },
  { id: 175, word: "User", pos: "n.", translation: "ผู้ใช้งาน", example: "Active app user.", category: "Technology & Science" },
  { id: 176, word: "Video", pos: "n.", translation: "วิดีโอ", example: "Watch streaming video.", category: "Technology & Science" },
  { id: 177, word: "Audio", pos: "n.", translation: "เสียง", example: "Clear audio sound.", category: "Technology & Science" },
  { id: 178, word: "Signal", pos: "n.", translation: "สัญญาณ", example: "Strong Wi-Fi signal.", category: "Technology & Science" },
  { id: 179, word: "Search", pos: "v.", translation: "ค้นหา", example: "Search information online.", category: "Technology & Science" },
  { id: 180, word: "Click", pos: "v.", translation: "คลิก", example: "Click the blue button.", category: "Technology & Science" },
  { id: 181, word: "Press", pos: "v.", translation: "กด", example: "Press enter key.", category: "Technology & Science" },
  { id: 182, word: "Save", pos: "v.", translation: "บันทึก", example: "Save changes now.", category: "Technology & Science" },
  { id: 183, word: "Delete", pos: "v.", translation: "ลบ", example: "Delete old files.", category: "Technology & Science" },
  { id: 184, word: "Share", pos: "v.", translation: "แบ่งปัน", example: "Share post with friends.", category: "Technology & Science" },
  { id: 185, word: "Science", pos: "n.", translation: "วิทยาศาสตร์", example: "Study modern science.", category: "Technology & Science" },
  { id: 186, word: "Lab", pos: "n.", translation: "ห้องทดลอง", example: "Science research lab.", category: "Technology & Science" },
  { id: 187, word: "Light", pos: "n.", translation: "แสง", example: "Speed of bright light.", category: "Technology & Science" },
  { id: 188, word: "Sound", pos: "n.", translation: "เสียง", example: "Sound waves travel.", category: "Technology & Science" },
  { id: 189, word: "Planet", pos: "n.", translation: "ดาวเคราะห์", example: "Earth is our planet.", category: "Technology & Science" },
  { id: 190, word: "Star", pos: "n.", translation: "ดวงดาว", example: "Shining night star.", category: "Technology & Science" },
  { id: 191, word: "Moon", pos: "n.", translation: "ดวงจันทร์", example: "Full moon tonight.", category: "Technology & Science" },
  { id: 192, word: "Sun", pos: "n.", translation: "ดวงอาทิตย์", example: "Hot bright sun.", category: "Technology & Science" },
  { id: 193, word: "Earth", pos: "n.", translation: "โลก", example: "Protect planet Earth.", category: "Technology & Science" },
  { id: 194, word: "Nature", pos: "n.", translation: "ธรรมชาติ", example: "Beautiful green nature.", category: "Technology & Science" },
  { id: 195, word: "Machine", pos: "n.", translation: "เครื่องจักร", example: "Industrial factory machine.", category: "Technology & Science" },
  { id: 196, word: "Engine", pos: "n.", translation: "เครื่องยนต์", example: "Car engine power.", category: "Technology & Science" },
  { id: 197, word: "Power", pos: "n.", translation: "พลังงาน/อำนาจ", example: "Electric power plant.", category: "Technology & Science" },
  { id: 198, word: "Test", pos: "n.", translation: "การทดสอบ", example: "System accuracy test.", category: "Technology & Science" },
  { id: 199, word: "Result", pos: "n.", translation: "ผลลัพธ์", example: "Lab test results.", category: "Technology & Science" },
  { id: 200, word: "Future", pos: "n.", translation: "อนาคต", example: "Technology of future.", category: "Technology & Science" },

  // --- หมวด 5: Sports & Hobbies (กีฬาและงานอดิเรก) 50 คำ ---
  { id: 201, word: "Ball", pos: "n.", translation: "ลูกบอล", example: "Kick the leather ball.", category: "Sports & Hobbies" },
  { id: 202, word: "Game", pos: "n.", translation: "เกม", example: "Play fun board game.", category: "Sports & Hobbies" },
  { id: 203, word: "Goal", pos: "n.", translation: "ประตู/เป้าหมาย", example: "Score a winning goal.", category: "Sports & Hobbies" },
  { id: 204, word: "Music", pos: "n.", translation: "ดนตรี", example: "Listen to pop music.", category: "Sports & Hobbies" },
  { id: 205, word: "Song", pos: "n.", translation: "เพลง", example: "Sing a favorite song.", category: "Sports & Hobbies" },
  { id: 206, word: "Sport", pos: "n.", translation: "กีฬา", example: "Play outdoor sports.", category: "Sports & Hobbies" },
  { id: 207, word: "Team", pos: "n.", translation: "ทีม", example: "Winning football team.", category: "Sports & Hobbies" },
  { id: 208, word: "Swim", pos: "v.", translation: "ว่ายน้ำ", example: "Swim in pool.", category: "Sports & Hobbies" },
  { id: 209, word: "Play", pos: "v.", translation: "เล่น", example: "Play guitar daily.", category: "Sports & Hobbies" },
  { id: 210, word: "Sing", pos: "v.", translation: "ร้องเพลง", example: "Sing on stage.", category: "Sports & Hobbies" },
  { id: 211, word: "Art", pos: "n.", translation: "ศิลปะ", example: "Modern art gallery.", category: "Sports & Hobbies" },
  { id: 212, word: "Paint", pos: "v.", translation: "วาดภาพ/ระบายสี", example: "Paint a landscape.", category: "Sports & Hobbies" },
  { id: 213, word: "Draw", pos: "v.", translation: "วาดภาพ", example: "Draw cartoon characters.", category: "Sports & Hobbies" },
  { id: 214, word: "Book", pos: "n.", translation: "หนังสือ", example: "Read story book.", category: "Sports & Hobbies" },
  { id: 215, word: "Movie", pos: "n.", translation: "ภาพยนตร์", example: "Watch action movie.", category: "Sports & Hobbies" },
  { id: 216, word: "Football", pos: "n.", translation: "ฟุตบอล", example: "Play football weekend.", category: "Sports & Hobbies" },
  { id: 217, word: "Tennis", pos: "n.", translation: "เทนนิส", example: "Tennis match game.", category: "Sports & Hobbies" },
  { id: 218, word: "Running", pos: "n.", translation: "การวิ่ง", example: "Morning running habit.", category: "Sports & Hobbies" },
  { id: 219, word: "Yoga", pos: "n.", translation: "โยคะ", example: "Practice daily yoga.", category: "Sports & Hobbies" },
  { id: 220, word: "Guitar", pos: "n.", translation: "กีตาร์", example: "Acoustic wooden guitar.", category: "Sports & Hobbies" },
  { id: 221, word: "Piano", pos: "n.", translation: "เปียโน", example: "Play classical piano.", category: "Sports & Hobbies" },
  { id: 222, word: "Camera", pos: "n.", translation: "กล้อง", example: "Photography camera gear.", category: "Sports & Hobbies" },
  { id: 223, word: "Photo", pos: "n.", translation: "รูปภาพ", example: "Take a beautiful photo.", category: "Sports & Hobbies" },
  { id: 224, word: "Hobby", pos: "n.", translation: "งานอดิเรก", example: "Gardening is my hobby.", category: "Sports & Hobbies" },
  { id: 225, word: "Match", pos: "n.", translation: "การแข่งขัน", example: "Watch live match.", category: "Sports & Hobbies" },
  { id: 226, word: "Player", pos: "n.", translation: "ผู้เล่น", example: "Talented sports player.", category: "Sports & Hobbies" },
  { id: 227, word: "Win", pos: "v.", translation: "ชนะ", example: "Win gold medal.", category: "Sports & Hobbies" },
  { id: 228, word: "Lose", pos: "v.", translation: "แพ้", example: "Don't fear to lose.", category: "Sports & Hobbies" },
  { id: 229, word: "Score", pos: "n.", translation: "คะแนน", example: "High game score.", category: "Sports & Hobbies" },
  { id: 230, word: "Jump", pos: "v.", translation: "กระโดด", example: "Jump high over hurdle.", category: "Sports & Hobbies" },
  { id: 231, word: "Catch", pos: "v.", translation: "จับ/รับ", example: "Catch the ball.", category: "Sports & Hobbies" },
  { id: 232, word: "Throw", pos: "v.", translation: "ขว้าง", example: "Throw the frisbee.", category: "Sports & Hobbies" },
  { id: 233, word: "Hit", pos: "v.", translation: "ตี", example: "Hit baseball hard.", category: "Sports & Hobbies" },
  { id: 234, word: "Race", pos: "n.", translation: "การแข่งขันความเร็ว", example: "Car racing track.", category: "Sports & Hobbies" },
  { id: 235, word: "Pool", pos: "n.", translation: "สระว่ายน้ำ", example: "Deep swimming pool.", category: "Sports & Hobbies" },
  { id: 236, word: "Gym", pos: "n.", translation: "โรงยิม", example: "Workout at gym.", category: "Sports & Hobbies" },
  { id: 237, word: "Club", pos: "n.", translation: "ชมรม/สโมสร", example: "Join sports club.", category: "Sports & Hobbies" },
  { id: 238, word: "Fan", pos: "n.", translation: "แฟนคลับ", example: "Football club fan.", category: "Sports & Hobbies" },
  { id: 239, word: "Champion", pos: "n.", translation: "แชมป์/ผู้ชนะเลิศ", example: "World champion title.", category: "Sports & Hobbies" },
  { id: 240, word: "Exercise", pos: "v.", translation: "ออกกำลังกาย", example: "Exercise every morning.", category: "Sports & Hobbies" },
  { id: 241, word: "Camp", pos: "n.", translation: "ค่าย/การตั้งแคมป์", example: "Summer outdoor camp.", category: "Sports & Hobbies" },
  { id: 242, word: "Fish", pos: "v.", translation: "ตกปลา", example: "Fish by the lake.", category: "Sports & Hobbies" },
  { id: 243, word: "Climb", pos: "v.", translation: "ปีนป่าย", example: "Climb mountain wall.", category: "Sports & Hobbies" },
  { id: 244, word: "Cycle", pos: "v.", translation: "ปั่นจักรยาน", example: "Cycle around park.", category: "Sports & Hobbies" },
  { id: 245, word: "Walk", pos: "v.", translation: "เดินเล่น", example: "Evening walking tour.", category: "Sports & Hobbies" },
  { id: 246, word: "Craft", pos: "n.", translation: "งานฝีมือ", example: "Paper craft design.", category: "Sports & Hobbies" },
  { id: 247, word: "Chess", pos: "n.", translation: "หมากรุก", example: "Play chess strategy.", category: "Sports & Hobbies" },
  { id: 248, word: "Puzzle", pos: "n.", translation: "ปริศนาอักษรไขว้", example: "Solve jigsaw puzzle.", category: "Sports & Hobbies" },
  { id: 249, word: "Collection", pos: "n.", translation: "ของสะสม", example: "Stamp collection book.", category: "Sports & Hobbies" },
  { id: 250, word: "Fun", pos: "n.", translation: "ความสนุกสนาน", example: "Have fun today.", category: "Sports & Hobbies" },

  // --- หมวด 6: Feelings & Descriptions (ความรู้สึกและการอธิบาย) 50 คำ ---
  { id: 251, word: "Happy", pos: "adj.", translation: "มีความสุข", example: "Feel happy today.", category: "Feelings & Descriptions" },
  { id: 252, word: "Sad", pos: "adj.", translation: "เศร้า", example: "Sad movie story.", category: "Feelings & Descriptions" },
  { id: 253, word: "Angry", pos: "adj.", translation: "โกรธ", example: "Don't be angry.", category: "Feelings & Descriptions" },
  { id: 254, word: "Tired", pos: "adj.", translation: "เหนื่อย", example: "Tired after work.", category: "Feelings & Descriptions" },
  { id: 255, word: "Excited", pos: "adj.", translation: "ตื่นเต้น", example: "Excited about trip.", category: "Feelings & Descriptions" },
  { id: 256, word: "Big", pos: "adj.", translation: "ใหญ่", example: "Big elephant animal.", category: "Feelings & Descriptions" },
  { id: 257, word: "Small", pos: "adj.", translation: "เล็ก", example: "Small cute ant.", category: "Feelings & Descriptions" },
  { id: 258, word: "Good", pos: "adj.", translation: "ดี", example: "Have a good day.", category: "Feelings & Descriptions" },
  { id: 259, word: "Bad", pos: "adj.", translation: "แย่", example: "Bad rainy weather.", category: "Feelings & Descriptions" },
  { id: 260, word: "Hot", pos: "adj.", translation: "ร้อน", example: "Hot summer day.", category: "Feelings & Descriptions" },
  { id: 261, word: "Cold", pos: "adj.", translation: "หนาว", example: "Cold winter ice.", category: "Feelings & Descriptions" },
  { id: 262, word: "Fast", pos: "adj.", translation: "เร็ว", example: "Fast sports car.", category: "Feelings & Descriptions" },
  { id: 263, word: "Slow", pos: "adj.", translation: "ช้า", example: "Slow crawling turtle.", category: "Feelings & Descriptions" },
  { id: 264, word: "Beautiful", pos: "adj.", translation: "สวยงาม", example: "Beautiful flower blossom.", category: "Feelings & Descriptions" },
  { id: 265, word: "New", pos: "adj.", translation: "ใหม่", example: "Buy new shoes.", category: "Feelings & Descriptions" },
  { id: 266, word: "Old", pos: "adj.", translation: "เก่า/แก่", example: "Old historical building.", category: "Feelings & Descriptions" },
  { id: 267, word: "Young", pos: "adj.", translation: "อายุน้อย", example: "Young energetic child.", category: "Feelings & Descriptions" },
  { id: 268, word: "Brave", pos: "adj.", translation: "กล้าหาญ", example: "Brave firefighter hero.", category: "Feelings & Descriptions" },
  { id: 269, word: "Calm", pos: "adj.", translation: "สงบ", example: "Calm quiet sea.", category: "Feelings & Descriptions" },
  { id: 270, word: "Smart", pos: "adj.", translation: "ฉลาด", example: "Smart student boy.", category: "Feelings & Descriptions" },
  { id: 271, word: "Kind", pos: "adj.", translation: "ใจดี", example: "Kind helpful nurse.", category: "Feelings & Descriptions" },
  { id: 272, word: "Rich", pos: "adj.", translation: "รวย", example: "Rich business man.", category: "Feelings & Descriptions" },
  { id: 273, word: "Poor", pos: "adj.", translation: "ยากจน", example: "Help poor people.", category: "Feelings & Descriptions" },
  { id: 274, word: "Clean", pos: "adj.", translation: "สะอาด", example: "Clean fresh air.", category: "Feelings & Descriptions" },
  { id: 275, word: "Dirty", pos: "adj.", translation: "สกปรก", example: "Dirty muddy shoes.", category: "Feelings & Descriptions" },
  { id: 276, word: "Easy", pos: "adj.", translation: "ง่าย", example: "Easy quiz question.", category: "Feelings & Descriptions" },
  { id: 277, word: "Hard", pos: "adj.", translation: "ยาก/แข็ง", example: "Hard math exam.", category: "Feelings & Descriptions" },
  { id: 278, word: "Heavy", pos: "adj.", translation: "หนัก", example: "Heavy luggage bag.", category: "Feelings & Descriptions" },
  { id: 279, word: "Light", pos: "adj.", translation: "เบา", example: "Light bird feather.", category: "Feelings & Descriptions" },
  { id: 280, word: "Long", pos: "adj.", translation: "ยาว", example: "Long winding road.", category: "Feelings & Descriptions" },
  { id: 281, word: "Short", pos: "adj.", translation: "สั้น/เตี้ย", example: "Short break time.", category: "Feelings & Descriptions" },
  { id: 282, word: "Tall", pos: "adj.", translation: "สูง", example: "Tall green tree.", category: "Feelings & Descriptions" },
  { id: 283, word: "Strong", pos: "adj.", translation: "แข็งแรง", example: "Strong gym athlete.", category: "Feelings & Descriptions" },
  { id: 284, word: "Weak", pos: "adj.", translation: "อ่อนแอ", example: "Weak sick patient.", category: "Feelings & Descriptions" },
  { id: 285, word: "Bored", pos: "adj.", translation: "เบื่อ", example: "Feel bored at home.", category: "Feelings & Descriptions" },
  { id: 286, word: "Afraid", pos: "adj.", translation: "กลัว", example: "Afraid of dark.", category: "Feelings & Descriptions" },
  { id: 287, word: "Nervous", pos: "adj.", translation: "ประหม่า", example: "Nervous before test.", category: "Feelings & Descriptions" },
  { id: 288, word: "Proud", pos: "adj.", translation: "ภาคภูมิใจ", example: "Proud of success.", category: "Feelings & Descriptions" },
  { id: 289, word: "Surprised", pos: "adj.", translation: "ประหลาดใจ", example: "Surprised by gift.", category: "Feelings & Descriptions" },
  { id: 290, word: "Quiet", pos: "adj.", translation: "เงียบ", example: "Quiet library room.", category: "Feelings & Descriptions" },
  { id: 291, word: "Noisy", pos: "adj.", translation: "เสียงดัง", example: "Noisy city traffic.", category: "Feelings & Descriptions" },
  { id: 292, word: "Bright", pos: "adj.", translation: "สว่าง/สดใส", example: "Bright yellow sun.", category: "Feelings & Descriptions" },
  { id: 293, word: "Dark", pos: "adj.", translation: "มืด", example: "Dark night sky.", category: "Feelings & Descriptions" },
  { id: 294, word: "Sweet", pos: "adj.", translation: "อ่อนหวาน", example: "Sweet smile face.", category: "Feelings & Descriptions" },
  { id: 295, word: "Fresh", pos: "adj.", translation: "สดชื่น", example: "Fresh morning breeze.", category: "Feelings & Descriptions" },
  { id: 296, word: "Safe", pos: "adj.", translation: "ปลอดภัย", example: "Safe driving trip.", category: "Feelings & Descriptions" },
  { id: 297, word: "Dangerous", pos: "adj.", translation: "อันตราย", example: "Dangerous high cliff.", category: "Feelings & Descriptions" },
  { id: 298, word: "Famous", pos: "adj.", translation: "มีชื่อเสียง", example: "Famous movie star.", category: "Feelings & Descriptions" },
  { id: 299, word: "Perfect", pos: "adj.", translation: "สมบูรณ์แบบ", example: "Perfect score 100.", category: "Feelings & Descriptions" },
  { id: 300, word: "Ready", pos: "adj.", translation: "พร้อม", example: "Ready for adventure.", category: "Feelings & Descriptions" }
];